server:
  port: 8080
  servlet:
    context-path: /api
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show-sql: false
        ddl-auto:
          hbm2ddl:
            auto: validate
